### ISSUE TITLE
PHP 7.1.5

### ISSUE THREAD

**Issue by jrob24** [9whirls/webcommander_walnut#1]
Does webCommander_walnut work with PHP 7.1.5? Has it been tested? We have to upgrade from 5.3 due to vulnerabilities.

**Comment by 9whirls** [comment]
Today, I upgraded php from 5.6 to 7.1.6 on my laptop and tested a few commands without finding any problem.  So from webcommander perspective, the upgrade should be fine. 
However, I'm not sure what version of IIS (mine is 10) is fully compatible with php 7.1.6. You may want to check with microsoft.
