### ISSUE TITLE
Local or Remote scripts are not showing in webcommander. 

### ISSUE THREAD

**Issue by saaifali** [9whirls/webcommander_walnut#2]
Hey, Any of my scripts, local or remote are not being shown in webcommander. I cant figure out if it is a front end issue or something else. The following is the body of my index.html downloaded from here itself. 
A screenshot of the index page  - 
![image](https://user-images.githubusercontent.com/20296853/38011318-d696c856-3211-11e8-95b9-e48844c842af.png)

`<body>
<div id="header">
  <div id="logo">
    <a href="#" class="logo">web<span>Commander</span></a>
  </div>
  <div id="execute" class="shadow">
    <a href="/history.php" target="_blank"><i class="fa fa-history" aria-hidden="true" title="Execution history"></i></a>
    <i id="rerun" class="fa fa-fw fa-refresh" title="Start / stop re-run"></i>
    <i id="import" class="fa fa-fw fa-file-text" title="Import from JSON"></i>
    <i id="export" class="fa fa-fw fa-file-text-o" title="Export to JSON"></i>
    <i id="serial" class="fa fa-fw fa-cog" title="Run in serial"></i>
    <i id="parallel" class="fa fa-fw fa-cogs" title="Run in parallel"></i>
    <i id="toggleAll" class="fa fa-fw fa-toggle-down" title="Toggle display all commands"></i>
    <i id="onOffAll" class="fa fa-fw fa-toggle-on" title="Enable / Disable all commands"></i>
    <i id="autoDisable" class="fa fa-fw fa-check-square-o" title="Automatically disable passed commands"></i>
  </div>
</div>
<div id="sortable"></div>

</body>`

**Comment by 9whirls** [comment]
It looks that you have some issues to load javascripts.
Open the developer console in your browser to figure out what files couldn't be loaded.

**Comment by saaifali** [comment]
![image](https://user-images.githubusercontent.com/20296853/38072517-4e7045cc-3344-11e8-8e2f-f67e392f6e99.png)

This is my console when I load the page.  Does any of these links load the commands onto the site?

**Comment by 9whirls** [comment]
I saw multiple issues in the screenshot. But first of all the 500 error of exec.php is the most important.
You need to figure out why your IIS gives this error by browsing /exec.php locally on the IIS server. IIS will only show details when user view the page locally.

**Comment by saaifali** [comment]
I finally got it. There was an issue with the PHP version being used. Changing the PHP version from 5.3 to 5.6 did the trick.  It works now.
