### ISSUE TITLE
No documentation for adding local scripts and what to modify in them. 

### ISSUE THREAD

**Issue by saaifali** [9whirls/webcommander_walnut#3]
Hey, there is no document on what to do if i have my own scripts to add to webcommander. If there is, I cant find any. Can anyone please provide some sort of direction as to how we can put our own powershell scripts on Webcommander.

**Comment by 9whirls** [comment]
Hi, 
1. put your scripts under webcommand/powershell/ or any sub folders
2. rename the scripts that you want to expose as interfaces.ps1
3. cd to webcommander/powershell folder
4. .\genDefJson.ps1

**Comment by saaifali** [comment]
Thanks a lot! :D

Yours faithfully,
Saif Ali,
